# ----
# Site

title: CarTrawler
description: CarTrawler Native SDK Documentation
url: 
google_analytics_key:
permalink: pretty

collections:
  section_introduction:
    title: Introduction
    position: 1
  section_integration:
    title: Integration
    position: 2
  section_usage:
    title: Usage
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - Android
  - iOS
