# ----
# Site

title: CarTrawler
description: CarTrawler Native SDK Documentation
url:
google_analytics_key:
permalink: pretty

collections_dir: _collections
collections:
  section_introduction:
    title: Introduction
    position: 1
    product: nativesdk
  section_ios:
    title: iOS
    position: 2
    product: nativesdk
  section_android:
    title: Android
    position: 3
    product: nativesdk
  section_style_guide:
    title: Style Guide
    position: 4
    product: nativesdk
  section_release_notes:
    title: Release notes
    position: 5
    product: nativesdk
  ondemand_ios:
    title: iOS
    position: 1
    product: ondemand

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: no-search

types:
  - Android
  - iOS
